[server]
headless = true
address = "127.0.0.1"
port = 8501

[theme]
primaryColor = "#0078D4"
backgroundColor = "#F5F5F5" 
secondaryBackgroundColor = "#FFFFFF"
textColor = "#252525"
font = "sans serif"
